include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    prefer_single_quotes: true
    avoid_print: true
    sort_constructors_first: true
    prefer_const_constructors: true
    unnecessary_this: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    curly_braces_in_flow_control_structures: true
    require_trailing_commas: true

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - lib/**.g.dart
    - lib/**.freezed.dart

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
