name: flutter_resultable
description: "A lightweight Result type for modeling success/failure in Flutter and Dart using sealed classes."
version: 0.0.3
homepage: https://github.com/ihdatech/flutter_resultable
repository: https://github.com/ihdatech/flutter_resultable
issue_tracker: https://github.com/ihdatech/flutter_resultable/issues
funding:
  - https://github.com/sponsors/ihdatech

topics:
  - result
  - either
  - functional
  - error-handling
  - flutter

environment:
  sdk: ^3.8.0

dependencies:
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  test: ^1.26.2
